name: Package and Publish Helm Charts

on:
  push:
    branches:
      - main   # Trigger when you push to 'main'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Package Helm charts
        run: |
          mkdir -p output
          helm package charts/* -d output

      - name: Create Helm repo index
        run: |
          helm repo index output --url https://<your-username>.github.io/<your-repo>

      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
